root: ./

structure:
  readme: README.md
  summary: SUMMARY.md
  folders:
    - label: "WELCOME TO SODAX"
      path: .
      files:
        - README.md
        - "README (1).md"

    - label: "💻 Developers"
      path: developers
      folders:
        - label: "📑 Deployments"
          path: deployments
          files:
            - README.md
            - mainnet.md
            - relayer-api-endpoints.md
            - solver-api-endpoints.md
            - xcall-scanner.md
            - solver-compatible-assets.md

        - label: "🛠️ SDKs"
          path: packages
          folders:
            - label: "@sodax/sdk"
              path: sdk/docs
              files:
                - README.md
                - SWAPS.md
                - MONEY_MARKET.md
                - BRIDGE.md
                - BACKEND_API.md
            - label: "@sodax/dapp-kit"
              path: dapp-kit
              files:
                - README.md
            - label: "@sodax/wallet-sdk-core"
              path: wallet-sdk-core
              files:
                - README.md
            - label: "@sodax/wallet-sdk-react"
              path: wallet-sdk-react
              files:
                - README.md

        - label: "📖 Technical Overview"
          path: technical-overview
          files:
            - README.md
            - asset-manager.md
            - generalized-messaging-protocol.md
            - hub-wallet-abstraction.md
            - intents.md
            - vault-token.md

        - label: "❓ FAQ"
          path: .
          files:
            - faq.md
